- name: setup frontend
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove the html folder
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: create the html folder
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory

  - name: download the file
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      path: /tmp/frontend.zip

  - name: extract the file
    ansible.builtin.unarchive:
      src: expense.conf
      dest: /usr/share/nginx/html 
      remote_src: yes

  - name: copy the conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: reload the service
    ansible.builtin.service:
      daemon-reload: true
      state: restarted
      name: nodejs 